In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df=pd.read_csv('17-cardekho.csv')

In [41]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [42]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [43]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.drop('car_name',axis=1,inplace=True)
df.drop('brand',axis=1,inplace=True)

In [44]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [45]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [46]:
num_features=[features for features in df.columns if df[features].dtype!='O']
print('Num of Numerical features:',len(num_features))
cat_features=[features for features in df.columns if df[features].dtype=='O']
print('Num of Categorical Features:',len(cat_features))
discrete_features=[features for features in num_features if len(df[features].unique())<=25]
print('Num of Discrete Feature:',len(discrete_features))
continuous_features=[features for features in num_features if features not in discrete_features]
print('Num of Continuous Features:',len(continuous_features))

Num of Numerical features: 7
Num of Categorical Features: 4
Num of Discrete Feature: 2
Num of Continuous Features: 5

In [47]:
from sklearn.model_selection import train_test_split

x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [48]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [49]:
len(df['model'].unique())

120

In [50]:
df.shape

(15411, 11)

In [51]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [52]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [53]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [54]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [55]:
num_features=x.select_dtypes(exclude='object').columns
onehot_columns=['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,onehot_columns),
        ('StandardScalar',numeric_transformer,num_features)
    ],remainder='passthrough'
)

In [56]:
x=preprocessor.fit_transform(x)

In [57]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((12328, 14), (3083, 14))

In [59]:
x_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

In [60]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [61]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [62]:
models={
    'Linear Regression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'K-Neighbors Regressor':KNeighborsRegressor(),
    'Decision Tree Regressor':DecisionTreeRegressor(),
    'Random Forest Regressor':RandomForestRegressor(),
    'AdaBoost Regressor':AdaBoostRegressor(),
    'Gradient Boosting':GradientBoostingRegressor()
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    
    print('- Root Mean Squared Error: {:.4f}'.format(model_train_rmse))
    print('- Mean Absolute Error:{:.4f}'.format(model_train_mae))
    print('- R2 Score:{:.4f}'.format(model_train_r2))
    
    print('----------------------------------')
    
    print('Model performance for training set')
    
    print('- Root Mean Squared Error:{:.4f}'.format(model_test_rmse))
    print('- Mean Absolute Error:{:.4f}'.format(model_test_mae))
    print('- R2 Score:{:.4f}'.format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error:268101.6071
- R2 Score:0.6218
----------------------------------
Model performance for training set
- Root Mean Squared Error:502543.5930
- Mean Absolute Error:279618.5794
- R2 Score:0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6710
- Mean Absolute Error:268099.2226
- R2 Score:0.6218
----------------------------------
Model performance for training set
- Root Mean Squared Error:502542.6696
- Mean Absolute Error:279614.7461
- R2 Score:0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3160
- Mean Absolute Error:268059.8015
- R2 Score:0.6218
----------------------------------
Model performance for training set
- Root Mean Squared Error:502533.8230
- Mean Absolute Error:279557.2169
- R2 Score:0.6645
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 325873.0088
- Mean Absolute Error:91425.4705
- R2 Score:0.8691
----------------------------------
Model performance for training set
- Root Mean Squared Error:253024.3951
- Mean Absolute Error:112526.3461
- R2 Score:0.9150
===================================


Decision Tree Regressor
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error:5164.8199
- R2 Score:0.9995
----------------------------------
Model performance for training set
- Root Mean Squared Error:309395.8949
- Mean Absolute Error:125339.5691
- R2 Score:0.8728
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 124937.7903
- Mean Absolute Error:39741.4871
- R2 Score:0.9808
----------------------------------
Model performance for training set
- Root Mean Squared Error:226999.9789
- Mean Absolute Error:101344.8928
- R2 Score:0.9315
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 444591.6628
- Mean Absolute Error:325089.9890
- R2 Score:0.7563
----------------------------------
Model performance for training set
- Root Mean Squared Error:474013.9222
- Mean Absolute Error:340112.8975
- R2 Score:0.7015
===================================


Gradient Boosting
Model performance for Training set
- Root Mean Squared Error: 204944.5104
- Mean Absolute Error:111709.5558
- R2 Score:0.9482
----------------------------------
Model performance for training set
- Root Mean Squared Error:255303.0535
- Mean Absolute Error:126336.5550
- R2 Score:0.9134
===================================

In [63]:
knn_params={'n_neighbors':[2,3,10,20,40,50]}
rf_params={'max_depth':[5,8,15,None,10],
           'max_features':[5,7,'auto',8],
           'min_samples_split':[2,8,15,20],
           'n_estimators':[100,200,500,1000]}
ada_params={
    "n_estimators":[50,60,70,80],
    "loss":['linear','square','exponential']}
params_grid={
    'n_estimators':[100,200,300],
    'learning_rate':[0.01,0.05,0,1],
    'max_depth':[3,4,5],
    'min_samples_split':[2,5,10],
    'subsample':[0.8,1.0]
}

In [64]:
randomcv_models=[('KNN',KNeighborsRegressor(),knn_params),
                 ("RF",RandomForestRegressor(),rf_params),
                 ('AdaBoost',AdaBoostRegressor(),ada_params),
                 ('GBR',GradientBoostingRegressor(),params_grid)
                 ]

In [65]:
from sklearn.model_selection import RandomizedSearchCV

model_param={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)
    random.fit(x_train,y_train)
    model_param[name]=random.best_params_
    
for model_name in model_param:
    print(f"------------- Best Params for {model_name}----------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits

c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 100 candidates, totalling 300 fits

c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
78 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
46 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [0.84750485 0.85711148        nan 0.81914231 0.76849437 0.83516694
        nan 0.8335273  0.78683868 0.85577255 0.832625   0.85461668
 0.77245255 0.85258432        nan        nan 0.83702888 0.84086505
 0.82856411 0.82579798 0.85083959        nan        nan 0.83260656
        nan 0.84798687 0.77322979 0.85760398 0.8322924  0.82437135
 0.84135809 0.84240539 0.83981628 0.83346561 0.82654655 0.85411929
 0.84707739 0.77203539 0.8464839  0.82978385        nan 0.85834651
 0.8449604  0.84117827 0.7822532  0.83297334 0.82705038 0.8220081
 0.83627872 0.85367079 0.83941896 0.79530754 0.84143689        nan
 0.85080519        nan 0.85018652 0.84644567        nan 0.85258365
 0.79208745        nan 0.82809164 0.84037121 0.84439381 0.85106509
 0.78455191 0.7654738  0.84370164        nan 0.80334214        nan
 0.82698702 0.83230739        nan        nan        nan 0.79032759
        nan 0.84598255        nan        nan 0.84186689        nan
        nan 0.837236          nan        nan 0.82793096        nan
 0.83437114 0.79570299 0.8536478  0.85372645 0.84993106 0.78199596
 0.86081866        nan 0.8557605  0.82217606]
  warnings.warn(
c:\Users\Win 11 Pro\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 12 is smaller than n_iter=100. Running 12 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 12 candidates, totalling 36 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
------------- Best Params for KNN----------------
{'n_neighbors': 10}
------------- Best Params for RF----------------
{'n_estimators': 200, 'min_samples_split': 2, 'max_features': 7, 'max_depth': None}
------------- Best Params for AdaBoost----------------
{'n_estimators': 60, 'loss': 'linear'}
------------- Best Params for GBR----------------
{'subsample': 1.0, 'n_estimators': 300, 'min_samples_split': 2, 'max_depth': 5, 'learning_rate': 0.05}

In [66]:
models={
    'Random Forest Regressor': RandomForestRegressor(n_estimators=200,min_samples_split=2,max_features=7,max_depth=None),
    'l-Neighbors Regressor':KNeighborsRegressor(n_neighbors=10),
    'AdaBoost Regressor':AdaBoostRegressor(n_estimators=60,loss='linear'),
    'GradientBoost Regressor':GradientBoostingRegressor(subsample=1.0,n_estimators=300,min_samples_split=2,max_depth=5,learning_rate=0.05)
    
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for training set')
    
    print('- Root Mean Squared Error:{:.4f}'.format(model_train_rmse))
    print('- Mean Absolute Error:{:.4f}'.format(model_train_mae))
    print('- R2 Score:{:.4f}'.format(model_train_r2))
    
    print('------------------------------------')
    
    print('Model Performance for test set')
    
    print('- Root Mean Squared Error:{:.4f}'.format(model_test_rmse))
    print('- Mean Absolute Error:{:.4f}'.format(model_test_mae))
    print('- R2 Score:{:.4f}'.format(model_test_r2))
    
    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for training set
- Root Mean Squared Error:133903.5707
- Mean Absolute Error:39326.2871
- R2 Score:0.9779
------------------------------------
Model Performance for test set
- Root Mean Squared Error:215419.5309
- Mean Absolute Error:98995.1081
- R2 Score:0.9384
===================================


l-Neighbors Regressor
Model performance for training set
- Root Mean Squared Error:363460.7706
- Mean Absolute Error:103472.0474
- R2 Score:0.8371
------------------------------------
Model Performance for test set
- Root Mean Squared Error:263888.0623
- Mean Absolute Error:117496.2131
- R2 Score:0.9075
===================================


AdaBoost Regressor
Model performance for training set
- Root Mean Squared Error:466472.2580
- Mean Absolute Error:369648.9046
- R2 Score:0.7317
------------------------------------
Model Performance for test set
- Root Mean Squared Error:501262.0226
- Mean Absolute Error:387767.3284
- R2 Score:0.6662
===================================


GradientBoost Regressor
Model performance for training set
- Root Mean Squared Error:119958.7747
- Mean Absolute Error:78602.6035
- R2 Score:0.9823
------------------------------------
Model Performance for test set
- Root Mean Squared Error:219369.8711
- Mean Absolute Error:101170.5648
- R2 Score:0.9361
===================================